
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'J\xe4\xc0\xe4\xe2\xd2\xcb\xa6\x9a\x13a\xc9\xc3\xf1\xb1\xea'
    
_lr_action_items = {'}':([2,7,8,12,20,26,29,31,],[-6,-4,-2,-3,-5,-20,31,-7,]),'NOWS_STRING':([0,2,5,8,9,17,20,26,27,31,],[6,-6,11,6,15,22,-5,6,22,-7,]),']':([10,11,17,21,22,23,24,25,27,30,],[19,-8,-20,-15,-19,28,-17,-18,-20,-16,]),',':([21,22,25,],[27,-19,-18,]),'{':([19,],[26,]),'[':([0,2,8,9,20,26,31,],[5,-6,5,17,-5,5,-7,]),'$end':([0,1,2,3,7,8,12,20,31,],[-20,0,-6,-1,-4,-2,-3,-5,-7,]),'=':([4,6,],[9,-13,]),';':([13,14,15,16,18,28,],[20,-10,-12,-9,-11,-14,]),'WS_STRING':([9,17,27,],[18,25,25,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'attributeValue':([9,],[13,]),'sectionName':([5,],[10,]),'arrayValue':([9,],[14,]),'section':([0,8,26,],[2,2,2,]),'configElements':([0,8,26,],[3,12,29,]),'attributeName':([0,8,26,],[4,4,4,]),'arrayElements':([17,27,],[23,30,]),'arrayElement':([17,27,],[21,21,]),'stringValue':([9,],[16,]),'config':([0,],[1,]),'empty':([0,8,17,26,27,],[7,7,24,7,24,]),'configElement':([0,8,26,],[8,8,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> config","S'",1,None,None,None),
  ('config -> configElements','config',1,'p_config','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',66),
  ('configElements -> configElement','configElements',1,'p_configElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',72),
  ('configElements -> configElement configElements','configElements',2,'p_configElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',73),
  ('configElements -> empty','configElements',1,'p_configElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',74),
  ('configElement -> attributeName = attributeValue ;','configElement',4,'p_configElement','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',80),
  ('configElement -> section','configElement',1,'p_configElement','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',81),
  ('section -> [ sectionName ] { configElements }','section',6,'p_section','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',87),
  ('sectionName -> NOWS_STRING','sectionName',1,'p_sectionName','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',93),
  ('attributeValue -> stringValue','attributeValue',1,'p_attributeValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',98),
  ('attributeValue -> arrayValue','attributeValue',1,'p_attributeValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',99),
  ('stringValue -> WS_STRING','stringValue',1,'p_stringValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',105),
  ('stringValue -> NOWS_STRING','stringValue',1,'p_stringValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',106),
  ('attributeName -> NOWS_STRING','attributeName',1,'p_attributeName','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',112),
  ('arrayValue -> [ arrayElements ]','arrayValue',3,'p_arrayValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',119),
  ('arrayElements -> arrayElement','arrayElements',1,'p_arrayElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',126),
  ('arrayElements -> arrayElement , arrayElements','arrayElements',3,'p_arrayElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',127),
  ('arrayElements -> empty','arrayElements',1,'p_arrayElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',128),
  ('arrayElement -> WS_STRING','arrayElement',1,'p_arrayElement','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',139),
  ('arrayElement -> NOWS_STRING','arrayElement',1,'p_arrayElement','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',140),
  ('empty -> <empty>','empty',0,'p_empty','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',148),
]
