
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'%C\xb4a,\xab\xb6i\xb5\xde\x01\x1a\x02/\x0e='
    
_lr_action_items = {':':([22,23,27,],[35,-26,-27,]),'}':([2,7,8,12,13,24,25,26,28,34,36,40,41,42,43,44,46,],[-6,-4,-2,-3,-30,-22,37,-24,-5,-30,-30,46,-28,-25,-29,-23,-7,]),'NOWS_STRING':([0,2,5,8,9,13,19,28,34,35,36,38,46,],[6,-6,11,6,17,23,30,-5,6,41,23,30,-7,]),']':([10,11,19,29,30,31,32,33,38,45,],[21,-8,-30,-16,-20,39,-18,-19,-30,-17,]),',':([24,29,30,33,41,42,43,],[36,38,-20,-19,-28,-25,-29,]),';':([14,15,16,17,18,20,37,39,],[28,-11,-10,-13,-9,-12,-21,-15,]),'{':([9,21,],[13,34,]),'WS_STRING':([9,13,19,35,36,38,],[20,27,33,43,27,33,]),'=':([4,6,],[9,-14,]),'[':([0,2,8,9,28,34,46,],[5,-6,5,19,-5,5,-7,]),'$end':([0,1,2,3,7,8,12,28,46,],[-30,0,-6,-1,-4,-2,-3,-5,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'dictKey':([13,36,],[22,22,]),'attributeValue':([9,],[14,]),'dictionary':([9,],[15,]),'sectionName':([5,],[10,]),'arrayElement':([19,38,],[29,29,]),'arrayValue':([9,],[16,]),'section':([0,8,34,],[2,2,2,]),'configElements':([0,8,34,],[3,12,40,]),'attributeName':([0,8,34,],[4,4,4,]),'arrayElements':([19,38,],[31,45,]),'dictValue':([35,],[42,]),'dictElement':([13,36,],[24,24,]),'dictElements':([13,36,],[25,44,]),'stringValue':([9,],[18,]),'config':([0,],[1,]),'empty':([0,8,13,19,34,36,38,],[7,7,26,32,7,26,32,]),'configElement':([0,8,34,],[8,8,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> config","S'",1,None,None,None),
  ('config -> configElements','config',1,'p_config','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',68),
  ('configElements -> configElement','configElements',1,'p_configElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',76),
  ('configElements -> configElement configElements','configElements',2,'p_configElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',77),
  ('configElements -> empty','configElements',1,'p_configElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',78),
  ('configElement -> attributeName = attributeValue ;','configElement',4,'p_configElement','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',93),
  ('configElement -> section','configElement',1,'p_configElement','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',94),
  ('section -> [ sectionName ] { configElements }','section',6,'p_section','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',117),
  ('sectionName -> NOWS_STRING','sectionName',1,'p_sectionName','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',128),
  ('attributeValue -> stringValue','attributeValue',1,'p_attributeValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',136),
  ('attributeValue -> arrayValue','attributeValue',1,'p_attributeValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',137),
  ('attributeValue -> dictionary','attributeValue',1,'p_attributeValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',138),
  ('stringValue -> WS_STRING','stringValue',1,'p_stringValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',146),
  ('stringValue -> NOWS_STRING','stringValue',1,'p_stringValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',147),
  ('attributeName -> NOWS_STRING','attributeName',1,'p_attributeName','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',155),
  ('arrayValue -> [ arrayElements ]','arrayValue',3,'p_arrayValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',164),
  ('arrayElements -> arrayElement','arrayElements',1,'p_arrayElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',173),
  ('arrayElements -> arrayElement , arrayElements','arrayElements',3,'p_arrayElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',174),
  ('arrayElements -> empty','arrayElements',1,'p_arrayElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',175),
  ('arrayElement -> WS_STRING','arrayElement',1,'p_arrayElement','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',189),
  ('arrayElement -> NOWS_STRING','arrayElement',1,'p_arrayElement','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',190),
  ('dictionary -> { dictElements }','dictionary',3,'p_dictionary','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',200),
  ('dictElements -> dictElement','dictElements',1,'p_dictElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',206),
  ('dictElements -> dictElement , dictElements','dictElements',3,'p_dictElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',207),
  ('dictElements -> empty','dictElements',1,'p_dictElements','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',208),
  ('dictElement -> dictKey : dictValue','dictElement',3,'p_dictElement','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',226),
  ('dictKey -> NOWS_STRING','dictKey',1,'p_dictKey','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',235),
  ('dictKey -> WS_STRING','dictKey',1,'p_dictKey','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',236),
  ('dictValue -> NOWS_STRING','dictValue',1,'p_dictValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',242),
  ('dictValue -> WS_STRING','dictValue',1,'p_dictValue','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',243),
  ('empty -> <empty>','empty',0,'p_empty','/home/proger/Documents/Programming/Python/StyleCop/src/config/ConfigParser.py',249),
]
