
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\t{\xdb<\xaa\x06\xde\x86\x83\x8ccn\\\xf1\n\xb1'
    
_lr_action_items = {'NOWS_STRING':([2,8,],[4,4,]),',':([4,5,6,],[-5,8,-4,]),'[':([0,],[2,]),'$end':([1,7,],[0,-1,]),']':([3,4,5,6,9,],[7,-5,-2,-4,-3,]),'WS_STRING':([2,8,],[6,6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'array':([0,],[1,]),'elements':([2,8,],[3,9,]),'element':([2,8,],[5,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> array","S'",1,None,None,None),
  ('array -> [ elements ]','array',3,'p_array','/home/proger/Documents/Programming/Python/StyleCop/src/config/parsers/ArrayParser.py',18),
  ('elements -> element','elements',1,'p_elements','/home/proger/Documents/Programming/Python/StyleCop/src/config/parsers/ArrayParser.py',24),
  ('elements -> element , elements','elements',3,'p_elements','/home/proger/Documents/Programming/Python/StyleCop/src/config/parsers/ArrayParser.py',25),
  ('element -> WS_STRING','element',1,'p_element','/home/proger/Documents/Programming/Python/StyleCop/src/config/parsers/ArrayParser.py',32),
  ('element -> NOWS_STRING','element',1,'p_element','/home/proger/Documents/Programming/Python/StyleCop/src/config/parsers/ArrayParser.py',33),
]
